config/routes.rb
Locadora::Application.routes.draw do
  
  resources :clientes 
  
  resources :alugueis do
    member do
     get 'finalizar_aluguel'
    end
  end
  
  resources :generos do
    member do
     get 'listar_filmes'
    end
  end

  resources :filmes

  get "home/index"

   root :to => 'home#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	validates :nome, :email, :presence => true
  validates :email, :format => /\b[a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\b/

	has_many :alugueis, :dependent => :destroy
	
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
def index
    @clientes = Cliente.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cliente }
    end
  end
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cliente }
    end
  end
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cliente }
    end
  end
  def edit
    @cliente = Cliente.find(params[:id])
  end
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render json: @cliente, status: :created, location: @cliente }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
    def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<h1>Listing clientes</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Email</th>
    <th>Aluguéis ativos</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.nome %></td>
    <td><%= cliente.email %></td>
    <td>
      <% cliente.alugueis.active.each do |aluguel| %>
        <ul>
          <li> <%= aluguel.data_saida %>                     
            <% aluguel.filmes.each do |filme| %>
              <ul>
                <li> <%= filme.nome %></li>
              </ul>
            <% end -%>   
          </li>
        </ul>
      <% end -%>
    </td>
    <td><%= link_to 'Show', cliente %></td>
    <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
    <td><%= link_to 'Destroy', cliente, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cliente', new_cliente_path %>
<%= link_to 'Back', "/" %>

app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @cliente.nome %>
</p>
<p>
  <b>Email:</b>
  <%= @cliente.email %>
</p>


<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>