config/routes.rb
Locadora::Application.routes.draw do
  
  resources :clientes 
  
  resources :alugueis do
    member do
     get 'finalizar_aluguel'
    end
  end
  
  resources :generos do
    member do
     get 'listar_filmes'
    end
  end

  resources :filmes

  get "home/index"

   root :to => 'home#index'

end

app/models/genero.rb
class Genero < ActiveRecord::Base
	validates :nome, :presence => true

	has_many :filmes
end

app/controllers/generos_controller.rb
class GenerosController < ApplicationController
  # GET /generos
  # GET /generos.json
  def index
    @generos = Genero.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @generos }
    end
  end

  # GET /generos/1
  # GET /generos/1.json
  def show
    @genero = Genero.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @genero }
    end
  end

  # GET /generos/new
  # GET /generos/new.json
  def new
    @genero = Genero.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @genero }
    end
  end

  # GET /generos/1/edit
  def edit
    @genero = Genero.find(params[:id])
  end

  # POST /generos
  # POST /generos.json
  def create
    @genero = Genero.new(params[:genero])

    respond_to do |format|
      if @genero.save
        format.html { redirect_to @genero, notice: 'Genero was successfully created.' }
        format.json { render json: @genero, status: :created, location: @genero }
      else
        format.html { render action: "new" }
        format.json { render json: @genero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /generos/1
  # PUT /generos/1.json
  def update
    @genero = Genero.find(params[:id])

    respond_to do |format|
      if @genero.update_attributes(params[:genero])
        format.html { redirect_to @genero, notice: 'Genero was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @genero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generos/1
  # DELETE /generos/1.json
  def destroy
    @genero = Genero.find(params[:id])
    @genero.destroy

    respond_to do |format|
      format.html { redirect_to generos_url }
      format.json { head :no_content }
    end
  end
  def listar_filmes
    @genero = Genero.find(params[:id])
    @lista_filmes = @genero.filmes
  end
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/views/generos/_form.html.erb
<%= form_for(@genero) do |f| %>
  <% if @genero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genero.errors.count, "error") %> prohibited this genero from being saved:</h2>

      <ul>
      <% @genero.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/generos/edit.html.erb
<h1>Editing genero</h1>

<%= render 'form' %>

<%= link_to 'Show', @genero %> |
<%= link_to 'Back', generos_path %>

app/views/generos/index.html.erb
<h1>Listing generos</h1>

<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @generos.each do |genero| %>
  <tr>
    <td><%= genero.nome %></td>
    <td><%= link_to 'Show', genero %></td>
    <td><%= link_to 'Edit', edit_genero_path(genero) %></td>
    <td><%= link_to 'Destroy', genero, confirm: 'Are you sure?', method: :delete %></td>
    <td><%= link_to 'Listar filmes', listar_filmes_genero_path(genero) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Genero', new_genero_path %>
<%= link_to 'Back', "/" %>

app/views/generos/listar_filmes.html.erb
<h1>Listing filmes por gênero</h1>
<h2><%= @genero.nome %></h2>
<table>
  <tr>
    <th>Nome</th>
    <th>Ano</th>
    <th>Diretor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lista_filmes.each do |filme| %>
  <tr>
    <td><%= filme.nome %></td>
    <td><%= filme.ano %></td>
    <td><%= filme.diretor %></td>
    <td><%= link_to 'Show', filme %></td>
    <td><%= link_to 'Edit', edit_filme_path(filme) %></td>
    <td><%= link_to 'Destroy', filme, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Back', generos_path %>

app/views/generos/new.html.erb
<h1>New genero</h1>

<%= render 'form' %>

<%= link_to 'Back', generos_path %>

app/views/generos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @genero.nome %>
</p>


<%= link_to 'Edit', edit_genero_path(@genero) %> |
<%= link_to 'Back', generos_path %>