config/routes.rb
Locadora::Application.routes.draw do
  
  resources :clientes 
  
  resources :alugueis do
    member do
     get 'finalizar_aluguel'
    end
  end
  
  resources :generos do
    member do
     get 'listar_filmes'
    end
  end

  resources :filmes

  get "home/index"

   root :to => 'home#index'

end

app/models/genero.rb
class Genero < ActiveRecord::Base
	validates :nome, :presence => true

	has_many :filmes
end

app/controllers/alugueis_controller.rb
class AlugueisController < ApplicationController
	
  def index
    @alugueis = Aluguel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @alugueis }
    end
  end
  
  def show
    @aluguel = Aluguel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @aluguel }
    end
  end

  def new
    @movies = Filme.all
    @clients = Cliente.all
    @aluguel = Aluguel.new
    #@aluguel.data_saida = Time.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @aluguel }
    end
  end
  
  def edit
    @movies = Filme.all
    @clients = Cliente.all
    @aluguel = Aluguel.find(params[:id])
  end
  
  def create
    @aluguel = Aluguel.new(params[:aluguel])
    #@aluguel.data_saida = Time.now
    respond_to do |format|
      if @aluguel.save
        format.html { redirect_to @aluguel, notice: 'Aluguel was successfully created.' }
        format.json { render json: @aluguel, status: :created, location: @aluguel }
      else
        format.html { render action: "new" }
        format.json { render json: @aluguel.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    xopowo
    @aluguel = Aluguel.find(params[:id])

    respond_to do |format|
      if @aluguel.update_attributes(params[:aluguel])
        format.html { redirect_to @aluguel, notice: 'Aluguel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @aluguel.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @aluguel = Aluguel.find(params[:id])
    @aluguel.destroy

    respond_to do |format|
      format.html { redirect_to alugueis_url }
      format.json { head :no_content }
    end
  end	

  def finalizar_aluguel
    @aluguel = Aluguel.find(params[:id])    
    respond_to do |format|
      if @aluguel.finalizar!
        format.html { redirect_to @aluguel, notice: 'Aluguel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "show" }
        format.json { render json: @aluguel.errors, status: :unprocessable_entity }
      end
    end   
  end
end

app/helpers/alugueis_helper.rb
module AlugueisHelper
end

app/views/alugueis/_form.html.erb
<%= form_for @aluguel do |f| %>
  <% if @aluguel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aluguel.errors.count, "error") %> prohibited this aluguel from being saved:</h2>

      <ul>
      <% @aluguel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :cliente_id, 'Cliente:' %><br />
    <%= f.select("cliente_id", @clients.collect { |client| [ client.nome, client.id ] }, { :include_blank => true }) %>
  </div>
  <div class="field">
    <%= f.label :data_saida, 'Data de saída:' %><br />
    <%= f.text_field "data_saida" , :disabled => true %>
  </div>
  
  <div class="field">
    <%= hidden_field_tag "aluguel[filme_ids][]", "" %>
    <% @movies.each do |filme| -%>
    <div>
      <%= check_box_tag :filme_ids, filme.id, @aluguel.filmes.include?(filme), :name => 'aluguel[filme_ids][]' %>
      <%= f.label :filme_ids, filme.nome %><br />
    </div>
  <% end -%>
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alugueis/edit.html.erb
<h1>Editing filme</h1>

<%= render 'form' %>

<%= link_to 'Show', @filme %> |
<%= link_to 'Back', filmes_path %>

app/views/alugueis/index.html.erb
<h1>Listing Alugueis</h1>

<table>
  <tr>
    <th>Cliente</th>
    <th>Filmes</th>
    <th>Data de saída</th>
    <th>Data de entrega</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @alugueis.each do |aluguel| %>
  <tr>
    <td><%= aluguel.cliente.nome %></td>
    <td>
      <% aluguel.filmes.each do |filme| %>
        <ul>
          <li> <%= filme.nome %></li>
        </ul>
      <% end -%>
    </td>
    <td><%= aluguel.data_saida %></td>
    <td><%= aluguel.data_devolucao %></td>
    <td><%= link_to 'Show', aluguel %></td>
    <td><%= link_to 'Edit', edit_aluguel_path(aluguel) %></td>
    <td><%= link_to 'Destroy', aluguel, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New aluguel', new_aluguel_path %>
<%= link_to 'Back', "/" %>

app/views/alugueis/new.html.erb
<h1>New aluguel</h1>

<%= render 'form' %>

<%= link_to 'Back', alugueis_path %>

app/views/alugueis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cliente:</b>
  <%= @aluguel.cliente.nome %>
</p>

<p>
  <b>Filmes:</b>
  <% @aluguel.filmes.each do |filme| %>
  	<ul>
     	<li> <%= filme.nome %></li>
    </ul>
  <% end -%>
</p>

<p>
  <b>Data do aluguel:</b>
  <%= @aluguel.data_saida %>
</p>

<p>
  <b>Data da entrega:</b>
  <%= @aluguel.data_devolucao %>
</p>

<% if @aluguel.data_devolucao.nil? %>
  <%= link_to 'Finalizar aluguel', finalizar_aluguel_aluguel_path(@aluguel) %>
<% end %>
<%= link_to 'Back', alugueis_path %>