config/routes.rb
Locadora::Application.routes.draw do
  
  resources :clientes 
  
  resources :alugueis do
    member do
     get 'finalizar_aluguel'
    end
  end
  
  resources :generos do
    member do
     get 'listar_filmes'
    end
  end

  resources :filmes

  get "home/index"

   root :to => 'home#index'

end

app/models/filme.rb
class Filme < ActiveRecord::Base
	validates :nome, :genero, :presence => true
	validates :qtde, :presence => true, :numericality => { :only_integer => true, :greater_than => -1 }
	
	belongs_to :genero
	has_and_belongs_to_many :alugueis

	def qtde_disponivel
		self.qtde - self.alugueis.active.size
	end
end

app/controllers/filmes_controller.rb
class FilmesController < ApplicationController
  # GET /filmes
  # GET /filmes.json
  def index
    @filmes = Filme.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @filmes }
    end
  end

  # GET /filmes/1
  # GET /filmes/1.json
  def show
    @filme = Filme.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @filme }
    end
  end

  # GET /filmes/new
  # GET /filmes/new.json
  def new
    @filme = Filme.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @filme }
    end
  end

  # GET /filmes/1/edit
  def edit
    @filme = Filme.find(params[:id])
  end

  # POST /filmes
  # POST /filmes.json
  def create
    @filme = Filme.new(params[:filme])

    respond_to do |format|
      if @filme.save
        format.html { redirect_to @filme, notice: 'Filme was successfully created.' }
        format.json { render json: @filme, status: :created, location: @filme }
      else
        format.html { render action: "new" }
        format.json { render json: @filme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /filmes/1
  # PUT /filmes/1.json
  def update
    @filme = Filme.find(params[:id])

    respond_to do |format|
      if @filme.update_attributes(params[:filme])
        format.html { redirect_to @filme, notice: 'Filme was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @filme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filmes/1
  # DELETE /filmes/1.json
  def destroy
    @filme = Filme.find(params[:id])
    @filme.destroy

    respond_to do |format|
      format.html { redirect_to filmes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/filmes_helper.rb
module FilmesHelper
end

app/views/filmes/_form.html.erb
<%= form_for(@filme) do |f| %>
  <% if @filme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@filme.errors.count, "error") %> prohibited this filme from being saved:</h2>

      <ul>
      <% @filme.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome, 'Nome:' %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :ano, 'Ano:' %><br />
    <%= f.number_field :ano %>
  </div>
  <div class="field">
    <%= f.label :diretor, 'Diretor:' %><br />
    <%= f.text_field :diretor %>
  </div>
  <div class="field">
    <%= f.label :genero, 'Gênero' %><br />
    <%= f.select("genero_id", Genero.all.collect {|g| [ g.nome, g.id ] }, { :include_blank => true }) %>
  </div>
  <div class="field">
    <%= f.label :qtde, 'Quantidade:' %><br />
    <%= f.text_field :qtde %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/filmes/index.html.erb
<h1>Listing filmes</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Ano</th>
    <th>Diretor</th>
    <th>Gênero</th>
    <th>Quantidade total</th>
    <th>Quantidade disponível</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @filmes.each do |filme| %>
  <tr>
    <td><%= filme.nome %></td>
    <td><%= filme.ano %></td>
    <td><%= filme.diretor %></td>
    <td><%= filme.genero.nome %></td>
    <td><%= filme.qtde %></td>
    <td><%= filme.qtde_disponivel %></td>
    <td><%= link_to 'Show', filme %></td>
    <td><%= link_to 'Edit', edit_filme_path(filme) %></td>
    <td><%= link_to 'Destroy', filme, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Filme', new_filme_path %>
<%= link_to 'Back', "/" %>

app/views/filmes/new.html.erb
<h1>New filme</h1>

<%= render 'form' %>

<%= link_to 'Back', filmes_path %>

app/views/filmes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @filme.nome %>
</p>

<p>
  <b>Ano:</b>
  <%= @filme.ano %>
</p>

<p>
  <b>Diretor:</b>
  <%= @filme.diretor %>
</p>

<p>
  <b>Gênero:</b>
  <%= @filme.genero.nome %>
</p>

<p>
  <b>Quantidade:</b>
  <%= @filme.qtde %>
</p>

<p>
  <b>Quantidade disponível:</b>
  <%= @filme.qtde_disponivel %>
</p>


<%= link_to 'Edit', edit_filme_path(@filme) %> |
<%= link_to 'Back', filmes_path %>